using System;
using System.Collections.Generic;
using VMS.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using VMS.ViewModel;
using VMS.Helper;

namespace Mahamineral.ViewModel
{

    public class VMVehicleRelease : BaseModel
    {
        public VMVehicleRelease()
        {
            TransactionMessage = new TransactionMessageVM();
            CreatedOn = utilityHelper.CurrentDateTime;
            UpdatedOn = utilityHelper.CurrentDateTime;
        }

        public int Id { get; set; }

        public string? InwardSlipNo { get; set; }

        public string? WasheryName { get; set; }

        public string? WCLGatePassWasheryTicketNo  { get; set; }

        public string? TruckNumber { get; set; }

        public string? DriverName { get; set; }

        public string? Transporter { get; set; }

        public string? TransporterContactPerson { get; set; }

        public string? Date { get; set; }

        public bool WithoutSeal { get; set; }

        public bool DamagedGPS { get; set; }

        public bool WithoutGPS { get; set; }

        public bool MissingGPS { get; set; }

        public bool WithoutTarpaulin { get; set; }

        public bool WithUnfitTarpaulin { get; set; }

        public bool MoreThanNormalTime { get; set; }
        public bool IssueWithWCLKataParchi { get; set; }
        public bool DriverDrunkReported { get; set; }
        public bool OtherReason { get; set; }
        public bool? IsRateLongRoute { get; set; }
       
        public string? InwardTime { get; set; }

        public string? OutwardTime { get; set; }

        public string? InwardGrossWt { get; set; }

        public string? InwardTareWt { get; set; }

        public string? InwardNetWt { get; set; }

        public string? OutwardGrossWt { get; set; }

        public string? OutwardTareWt { get; set; }

        public string? OutwardNetWt { get; set; }

        public string? WasheryInTime { get; set; }

        public string? WasheryOutTime { get; set; }

        public decimal? WithoutsealAmount { get; set; }

        public decimal? Damagedgpsamount { get; set; }

        public decimal? Withoutgpsamount { get; set; }

        public decimal? Missinggpsamount { get; set; }

        public decimal? Withouttarpaulinamount { get; set; }

        public decimal? Withunfittarpaulinamount { get; set; }

        public decimal? Morethannormaltimeamount { get; set; }

        public decimal? Issuewithwasherykataparchiamount { get; set; }

        public decimal? Driverreporteddrunkamount { get; set; }

        public string? OtherReasonText { get; set; }

        public decimal? Otherreasonamount { get; set; }

        public string AutoGeneratedBillNo { get; set; }

        public decimal? Misccharges { get; set; }

        public string? TypeofAction { get; set; }

        public string? Source { get; set; }

        public string? NetWeight { get; set; }

        public string? Rate { get; set; }

        public string? DieselRate { get; set; }

        public DateOnly? SecurityDateTime { get; set; }

    }
}
