<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>38149b0d-1a29-4bb0-a744-1d10b7f20ecd</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\VehicleDriverController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.App" Version="2.2.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.OleDb" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\LRGRNOUpdateErrorFiles\" />
    <Folder Include="wwwroot\CompanyPan\" />
    <Folder Include="wwwroot\InsurancePhoto\" />
    <Folder Include="wwwroot\NationalPermitPhoto\" />
    <Folder Include="wwwroot\LocalPermitPhoto\" />
    <Folder Include="wwwroot\FitnessPhotoFolder\" />
    <Folder Include="wwwroot\PollutionDocPhotoFolder\" />
    <Folder Include="wwwroot\RtoDocPhotoFolder\" />
    <Folder Include="wwwroot\RcDocPhotoFolder\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\DriverHisab\Print.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
